- name: Install redis repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

- name: Enable redis 6 Module
  ansible.builtin.shell: dnf module enable redis:remi 6.2 -y

- name: Install redis
  ansible.buitlin.yum:
    name: redis
    state: present

- name: Update Redis Listen IP Address
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start and Enable Redis Service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes