- name: Print all RoboShop parameters
  hosts: localhost
  tasks:
    - name: Create value
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: "us-east-1"
      loop:
        - { name: "param.dev.catalogue.MONGO", value: "true" }
        - { name: "param.dev.catalogue.MONGO_ENDPOINT", value: "dev-mongodb.kingyamza.online"}
        - { name: "param.dev.user.MONGO", value: "true" }
        - { name: "param.dev.frontend.CATALOGUE_URL", value: "http://dev-catalogue.kingyamza.online:8080/" }
        - { name: "param.dev.frontend.USER_URL", value: "http://dev-user.kingyamza.online:8080/" }
        - { name: "param.dev.frontend.CART_URL", value: "http://dev-cart.kingyamza.online:8080/" }
        - { name: "param.dev.frontend.SHIPPING_URL", value: "http://dev-shipping.kingyamza.online:8080/" }
        - { name: "param.dev.frontend.PAYMENT_URL", value: "http://dev-payment.kingyamza.online:8080/" }