- name: Print all RoboShop parameters
  hosts: localhost
  tasks:
    - name: Create value
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: "us-east-1"
      loop:
        - { name: "param.dev.catalogue.MONGO", value: "true" }
        - { name: "param.dev.catalogue.MONGO_ENDPOINT", value: "dev-mongodb.kingyamza.online"}
        - { name: "param.dev.catalogue.MONGO_URL", value: "mongodb://dev-mongodb.kingyamza.online:27017/catalogue" }
        - { name: "param.dev.user.MONGO", value: "true" }
        - { name: "param.dev.frontend.CATALOGUE_URL", value: "http://dev-catalogue.kingyamza.online:8080/" }
        - { name: "param.dev.frontend.USER_URL", value: "http://dev-user.kingyamza.online:8080/" }
        - { name: "param.dev.frontend.CART_URL", value: "http://dev-cart.kingyamza.online:8080/" }
        - { name: "param.dev.frontend.SHIPPING_URL", value: "http://dev-shipping.kingyamza.online:8080/" }
        - { name: "param.dev.frontend.PAYMENT_URL", value: "http://dev-payment.kingyamza.online:8080/" }
        - { name: "param.dev.user.MONGO", value: "true" }
        - { name: "param.dev.user.MONGO_ENDPOINT", value: "dev-mongodb.kingyamza.online" }
        - { name: "param.dev.user.MONGO_URL", value: "mongodb://dev-mongodb.kingyamza.online:27017/user" }
        - { name: "param.dev.user.REDIS_HOST", value: "dev-redis.kingyamza.online" }
        - { name: "param.dev.cart.REDIS_HOST", value: "dev-redis.kingyamza.online" }
        - { name: "param.dev.cart.CATALOGUE_HOST", value: "dev-catalogue.kingyamza.online" }
        - { name: "param.dev.cart.CATALOGUE_PORT", value: "8080" }
        - { name: "param.dev.mysql.ROOT_PASSWORD", value: "RoboShop@1" }
        - { name: "param.dev.shipping.DB_HOST", value: "dev-mysql.kingyamza.online" }
        - { name: "param.dev.shipping.CART_ENDPOINT", value: "dev-cart.kingyamza.online:8080" }
        - { name: "param.dev.shipping.ROOT_PASSWORD", value: "RoboShop@1"}
        - { name: "param.dev.payment.USER_HOST", value: "dev-user.kingyamza.online"}
        - { name: "param.dev.payment.CART_HOST", value: "dev-cart.kingyamza.online"}
        - { name: "param.dev.payment.AMQP_HOST", value: "dev-rabbitmq.kingyamza.online"}
        - { name: "param.dev.payment.AMQP_USER", value: "roboshop"}
        - { name: "param.dev.payment.AMQP_PASS", value: "roboshop123"}
        - { name: "param.dev.rabbitmq.AMQP_PASS", value: "roboshop123"}
        - { name: "param.dev.rabbitmq.AMQP_USER", value: "roboshop"}