- name: Install Nginx Package
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Include App Tasks from Common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code

- name: Copy Roboshop Configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start and Enable Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes