- name: Copy Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart the service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: wait for 9090 to become open on the host, don't check for 5 seconds
  ansible.builtin.wait_for:
    port: 9090
    host: 0.0.0.0
    delay: 5
    timeout: 5