- name: Configure NodeJS repos
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Download app code Tasks from Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code

- name: Install NodeJS dependencies
  community.general.npm:
    path: "{{ APP_LOC }}"

- name: SystemD tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd